name: Update-Box64

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  update-box64:
    runs-on: ubuntu-24.04-arm

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Install dependencies and build (glibc 2.31)
        uses: docker://arm64v8/ubuntu:20.04
        with:
          entrypoint: "/bin/bash"
          args: -lc "
            set -euo pipefail;
            export DEBIAN_FRONTEND=noninteractive;
            apt-get update;
            apt-get install -y --no-install-recommends \
              ca-certificates build-essential git cmake ninja-build \
              pkg-config python3 curl wget jq checkinstall dpkg-dev \
              gpg gpg-agent gnupg lsb-release file binutils;
            echo 'GLIBC version:'; ldd --version | head -n1;
            cd /github/workspace;
            bash docker-script.sh;
            mkdir -p /github/workspace/out;
            cp -r *.deb /github/workspace/out/ || true;
            cp -r build/* /github/workspace/out/ || true;"
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: box64-$(date +'%Y%m%d')
          name: Box64 $(date +'%Y-%m-%d')
          body: "Automated build of Box64 with glibc 2.31 compatibility."
          files: out/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
